### ISSUE TITLE
Update ElasticSearch dependency to a more recent version

### ISSUE THREAD

**Issue by danielbraeutigam** [nebula-plugins/nebula-project-plugin#65]
We experienced a problem in conjunction with the OWASP dependency-check plugin (see https://github.com/jeremylong/DependencyCheck/issues/2909#issuecomment-712818813) . The reason for this seems to be an old dependency of ElasticSearch and therefore Lucene, which is more than 5 years old. 

Is it possible to update the dependency to a more recent version to avoid this conflict in classpath?

**Comment by danielbraeutigam** [comment]
@rpalcolea Any news on this? Seems like you are updating gradle versions on regular bases. Can you please answer my question?

**Comment by hpoettker** [comment]
The problem should already be fixed by the commit https://github.com/nebula-plugins/nebula-project-plugin/commit/b5bbf528a916d2277627b40535be0b40a8a5f251

The outdated ElasticSearch dependency was imported from `gradle-metrics-plugin` that is by now archived and no longer a part of `gradle-dependency-lock-plugin`.

A release with the updated dependencies would be really appreciated.

**Comment by rpalcolea** [comment]
Hi @hpoettker , thanks for the heads up! closing this now
